### ISSUE TITLE
Ability to update schemas in-place

### ISSUE THREAD

**Issue by probablyup** [sanity-io/contentful-to-sanity#15]
Currently the tool requires an empty directory and bootstraps the whole project for you. It would be great if there was a flag to skip the module setup and such and just synthesize schemas & upload. (This mostly comes into play when you're first starting out and find out you need to set up `--weak-refs` or something and then have to delete the whole folder and start over.)

**Comment by runeb** [comment]
This has now been updated in the latest versions and you can now generate just the schemas
