### ISSUE TITLE
document referenced from two places breaks migratoin

### ISSUE THREAD

**Issue by m0rph13** [sanity-io/contentful-to-sanity#3]
A contentful content "yyyy" is referenced from two other contents.
During migration, we encounter the error
" Document by ID "3c1u0fJ5fWSkIe0IGGSywU" already exists" which possibly could be due to the double usage?

**Comment by rexxars** [comment]
This seems odd. Could it be that you are importing to a dataset with existing documents in it? 
If so, using `--replace` or `--missing` (see documentation) should help you progress further.
