### ISSUE TITLE
Error: Unhandled data type "Integer" with widget "rating"

### ISSUE THREAD

**Issue by jgillich** [sanity-io/contentful-to-sanity#4]
Integers in Contentful can have a "rating" editor type where you select a number of stars. This appears to be unsupported, causing the import to fail:

    Error: Unhandled data type "Integer" with widget "rating" for field "..." of type "..."

Converting this to a regular integer input field would probably be fine since I assume Sanity has no equivalent.

**Comment by runeb** [comment]
Fix for this is on the way

**Comment by runeb** [comment]
This is an old issue which has been fixed for a while
