### ISSUE TITLE
Mismatch between types in Contenful and Sanity. (Migration from Contentful to Sanity).

### ISSUE THREAD

**Issue by asleboon** [sanity-io/contentful-to-sanity#8]
I Recieve the error when I try to run the contentful-to-sanity migration tool.

`
Error: Unhandled data type "Boolean" with widget "undefined" for field "menuDivider" of type "menuItemPrimary"
`

Here are some of the definitions that might be helpful from the export file (created with contentful-cli):

        {
          "id": "menuDivider",
          "name": "Add a menu divider",
          "type": "Boolean",
          "localized": false,
          "required": false,
          "validations": [],
          "disabled": false,
          "omitted": false
        }

```
{
          "id": "primaryMenuItems",
          "name": "Menu items",
          "type": "Array",
          "localized": false,
          "required": true,
          "validations": [],
          "disabled": false,
          "omitted": false,
          "items": {
            "type": "Link",
            "validations": [
              {
                "linkContentType": ["menuDivider", "menuItemPrimary"]
              }
            ],
            "linkType": "Entry"
          }
        }

**Comment by asleboon** [comment]
If necessary I can provide more details about the export file in a pm.

**Comment by runeb** [comment]
Hi @asleboon . I realize this issue was created a while ago, but if you have the `editorInterfaces` part of the export it would be helpful to see that in order to fix this issue.
